### ISSUE TITLE
update API Schema

### ISSUE THREAD

**Issue by zenlex** [tulsawebdevs/services-voting#34]
- [x] Remove create/update/delete routes for topics & projects (will all be considered proposals for creation and management, so only get routes are needed to filter by type and status)
- [x] Convert ids from strings to ints
- [x] add userId (email) to vote schema
- [x] return optional author with proposal

**Comment by Yi-Wu-3452** [comment]
Hi, zenlex. I'd love to help.

**Comment by zenlex** [comment]
Alec did a good amount of work on revising the schema on the frontend so for now we're just building this service to support the frontend and not worrying about CMS/Admin functionality
